### ISSUE TITLE
HttpProvider should throw an error if it receives an invalid error

### ISSUE THREAD

**Issue by vilsbole** [MyCryptoHQ/eth-scan#107]
Currently I can pass an object to HttpProvider which creates a cryptic error:
```t.reduce is not a function```

I expect the provider to fail if it receives and invalid url string.

**Comment by Mrtenz** [comment]
You shouldn't be able to use an object as URL if you're using TypeScript. Do you mean implementing actual runtime input validation?

**Comment by vilsbole** [comment]
Currently I don't get a TS error:
<img width="514" alt="Screenshot 2019-08-09 at 19 42 19" src="https://user-images.githubusercontent.com/2429708/62798163-e2f8b680-badd-11e9-8ce5-a8ae0c6ef33b.png">

Maybe because it's (correctly) serving the minified production version?

**Comment by Mrtenz** [comment]
Looks like your IDE can't find the TS types for some reason?

![](https://i.morten.dev/194476eb5ceb1d45.png)

What IDE are you using?

**Comment by vilsbole** [comment]
Atom
The types are included in the project right?
If it’s my IDE that is badly configured then feel free to close the issue.


On August 9, 2019 at 19:53:27, Maarten Zuidhoorn (notifications@github.com)
wrote:

Looks like your IDE can't find the TS types for some reason?

<https://camo.githubusercontent.com/43087222187c3e5d94499f4cb7cae4bf19a97bd8/68747470733a2f2f692e6d6f7274656e2e6465762f313934343736656235636562316434352e706e67>

What IDE are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MyCryptoHQ/eth-scan/issues/107?email_source=notifications&email_token=AASRGDBL4O7U3U5DD5LHZWTQDWVJPA5CNFSM4IKV6IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD37LFPY#issuecomment-520008383>,
or mute the thread

**Comment by Mrtenz** [comment]
The types are included in the published version and it works fine for me on IntelliJ IDEA, so it seems like it's an issue with your IDE.
