### ISSUE TITLE
Export BalanceMap interface

### ISSUE THREAD

**Issue by vilsbole** [MyCryptoHQ/eth-scan#127]
To avoid having to redefine the return type, it would be nice to be able to import the `BalanceMap` interface

**Comment by Mrtenz** [comment]
`BalanceMap` is exported here: https://github.com/MyCryptoHQ/eth-scan/blob/next/src/EthScan.ts#L17

Is it not available in the production build?

**Comment by vilsbole** [comment]
Yes, but it's not reexported in the `index.ts`
https://github.com/MyCryptoHQ/eth-scan/blob/next/src/index.ts#L2

<img width="703" alt="Screenshot 2019-09-07 at 14 55 58" src="https://user-images.githubusercontent.com/2429708/64475190-a45b2800-d17f-11e9-8a3d-8f6144074402.png">

**Comment by Mrtenz** [comment]
Available as `@mycrypto/eth-scan@1.0.1`.
