### ISSUE TITLE
getTokenBalances & getTokensBalances | Not functional

### ISSUE THREAD

**Issue by RyRy79261** [MyCryptoHQ/eth-scan#181]
## Description

When executing either `getTokensBalances` or `getTokenBalances` with either a `Web3` provider or a RPC endpoint, the following error occurs @ `eth-scan.ts:85`

Connection via metamask

```Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.0.0-beta.134) (argument=null, value=undefined, code=INVALID_ARGUMENT, version=abi/5.0.0-beta.145)```

**Comment by Mrtenz** [comment]
What do you call the functions with?

**Comment by RyRy79261** [comment]
I used a metamask current provider & an Infura rpc url. 

I manually passed the address of the metamask account in and as a token I used the SNT token as a test address (0x744d70fdbe2ba4cf95131626614a1763df805b9e) 

I suspect there might be something a miss with how I'm compiling but I wasn't able to investigate the stack trace further than that

**Comment by Mrtenz** [comment]
Please provide a reproducable example, as I am not able to reproduce this. This works fine for example:

```ts
import { getTokenBalances } from '@mycrypto/eth-scan';

getTokenBalances('https://api.mycryptoapi.com/eth', ['0xbbf0cc1c63f509d48a4674e270d26d80ccaf6022'], '0x744d70fdbe2ba4cf95131626614a1763df805b9e')
  .then(console.log)
  .catch(console.error);

// Results in:
// {
//  '0xbbf0cc1c63f509d48a4674e270d26d80ccaf6022': BigNumber { _hex:
//  '0x06605e51e489daf5ac88c0b9', _isBigNumber: true }
// }
```

**Comment by RyRy79261** [comment]
Thanks @Mrtenz, the snippet worked

I think there might be a state issue on my end, closing ticket
