### ISSUE TITLE
BSC

### ISSUE THREAD

**Issue by gajus** [MyCryptoHQ/eth-scan#226]
I have discovered this library through this [StackExchange question](https://ethereum.stackexchange.com/questions/98105/get-list-of-tokens-balances-from-wallet-address-via-web3).

Your last comment said:

> The contract is currently not deployed on BSC, but assuming BSC is compatible with EVM smart contracts, it should work as well if the contract was deployed.

Have you by any chance deployed equivalent contract to BSC network?

**Comment by Mrtenz** [comment]
I haven't deployed it on BSC yet, since I don't have any funds on BSC and we don't need it for BSC on MyCrypto at the moment. If you're able to provide some, I'd be happy to deploy it there? It needs about 724,261 gas to deploy.

**Comment by gajus** [comment]
I will try to do it as a learning exercise and will report back.

**Comment by Mrtenz** [comment]
Sure! In that case the contract different will be different though, so if you want to use it, you'll have to specify the contract address manually.

**Comment by gajus** [comment]
> Sure! In that case the contract different will be different though, so if you want to use it, you'll have to specify the contract address manually.

Just as a quick update, I ended up not needing this because https://github.com/devgoeth/ethereum-bsc-multicall performs equivalent functionality.

**Comment by Mrtenz** [comment]
Ok, in that case I think this issue can be closed.
