### ISSUE TITLE
Can the version of tron be deployed? I can provide gas

### ISSUE THREAD

**Issue by wenre** [MyCryptoHQ/eth-scan#228]
Can the version of tron be deployed? I can provide gas

**Comment by Mrtenz** [comment]
I'm not too familiar with Tron. If it's EVM-compatible I can deploy it for you on the Tron network?

**Comment by wenre** [comment]
It seems to be compatible with EVM

**Comment by Mrtenz** [comment]
I looked at it a bit more, and it looks like Tron is using a completely different format for addresses. I don't think `eth-scan` supports this, and either way it won't be possible to deploy the contract on the same address as used for Etherreum, xDai, etc. Feel free to deploy the contract yourself to see if it works.
