### ISSUE TITLE
Error on BSC: Failed to get data from contract: Error: Input must be hexadecimal

### ISSUE THREAD

**Issue by tskweres** [MyCryptoHQ/eth-scan#232]
Getting balances works great on ETH, but if I switch to BSC and pass a list of valid contract addresses, i see:

Failed to get data from contract: Error: Input must be hexadecimal

I use ethersproject/address to validate each address, and I'm using popular known contract addresses like BUSD, but it still fails. 

Any ideas?

**Comment by Mrtenz** [comment]
Can you please share some code to reproduce the issue?

**Comment by tskweres** [comment]
Will close this out, but the issue was the BSC RPC Endpoint. Changed to:

https://bsc-dataseed.binance.org/

Works great.
