### ISSUE TITLE
Minimal project with your example code throws an exception about importing uuid-random-es.js

### ISSUE THREAD

**Issue by gibbinator** [MyCryptoHQ/eth-scan#237]
Hi there!

I really want to use your library in my project, but am currently experiencing the following exception:

**package.json:
{
  "name": "eth-scanner",
  "version": "1.0.0",
  "main": "./lib/index.js",
  "bin": {
    "chain-inspector": "./lib/index.js"
  },
  "license": "MIT",
  "dependencies": {
    "@mycrypto/eth-scan": "^3.5.2"
  },
  "devDependencies": {
    "@types/node": "^16.9.6",
    "ts-node": "^10.2.1",
    "typescript": "^4.4.3"
  }
}

**tsconfig.json:
{
    "compilerOptions": {
      "target": "es2019",
      "module": "commonjs",
      "lib": ["es6", "es2015", "dom"],
      "declaration": true,
      "outDir": "lib",
      "rootDir": "src",
      "strict": true,
      "types": ["node"],
      "esModuleInterop": true,
      "resolveJsonModule": true,
      "moduleResolution": "node",
      "allowSyntheticDefaultImports": true,
     }
  }

**index.ts:
#!/usr/bin/env node
import { getEtherBalances } from '@mycrypto/eth-scan';

(async() => {
  
    getEtherBalances('http://192.168.155:8545', [
        '0x9a0decaffb07fb500ff7e5d253b16892dbec006a',
        '0xeb65f72a2f5464157288ac15f1bb56c56e6be375',
        '0x1b96c634f9e9fcfb76932e165984901701352ffd',
        '0x740539b55ee5dc58efffb88fea44a9008f8daa6f',
        '0x95d9e32dc03770699a6a5e5858165b174d500015'
      ]).then(console.log);

    })();

**result:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/gibbinator/code/eth-scanner-2/node_modules/uuid-random-es/dist/uuid-random-es.js from /Users/gibbinator/code/eth-scanner-2/node_modules/@mycrypto/eth-scan/lib/cjs/providers/http.js not supported.

Thanks very much,
Gibbinator

**Comment by Mrtenz** [comment]
Looks like this is caused by [a change we did recently](https://github.com/MyCryptoHQ/eth-scan/commit/f1bc0faf9f5ea2cf6fa97f59d9d2f2776a4b3c98#diff-8938c9905318fff75b54cf9f0e0f185f5c9ad7c0a22f57b912db7e42c9a04a15R62), where we use `uuid-random-es` to generate random JSON-RPC request IDs. It works with the ES/browser build, but not in the Node.js build. Thanks for the heads up, I'll swap this library out with another UUID library that works with Node.js as well.

**Comment by gibbinator** [comment]
Understandable, thanks for your attention.

**Comment by Mrtenz** [comment]
I swapped out `uuid-random-es` for `nanoid` (which is actually slightly smaller too), and published a new version as `@mycrypto/eth-scan@3.5.3`. Let me know if that works for you!
